#define CONSUMER_DEFAULT_PERIOD   (1)
#define RABBITMQ_DEFAULT_HOST     ("localhost")
#define RABBITMQ_DEFAULT_PORT     (5672)
#define RABBITMQ_DEFAULT_QUEUE    ("machine-translations")
#define RABBITMQ_DEFAULT_USERNAME ("guest")
#define RABBITMQ_DEFAULT_PASSWORD ("guest")
